### ISSUE TITLE
Script does not run in either Python 2.7 or 3

### ISSUE THREAD

**Issue by liar666** [maldevel/EmailHarvester#28]
I've just cloned the latest code...

$ python3 ./EmailHarvester.py  -d news.com.au 
[+] User-Agent in use: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1
[+] Searching everywhere
Traceback (most recent call last):
  File "./EmailHarvester.py", line 273, in <module>
    all_emails += plugins[search_engine]['search'](domain, limit)
  File "plugins/dogpile.py", line 31, in search
    app_emailharvester.process()
  File "./EmailHarvester.py", line 145, in process
    self.do_search()
  File "./EmailHarvester.py", line 140, in do_search
    self.results = r.content.decode(r.encoding)
TypeError: decode() argument 1 must be str, not None

$ python2.7 ./EmailHarvester.py  -d news.com.au 
Traceback (most recent call last):
  File "./EmailHarvester.py", line 47, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by maldevel** [comment]
python3 EmailHarvester.py -d example.com -e google
