### ISSUE TITLE
Problem with dogpile

### ISSUE THREAD

**Issue by TheWithz** [maldevel/EmailHarvester#29]
When running the program with -e dogpile or -e all I encounter this error

Traceback (most recent call last):
  File "EmailHarvester.py", line 273, in <module>
    all_emails += plugins[search_engine]['search'](domain, limit)
  File "plugins/dogpile.py", line 31, in search
    app_emailharvester.process()
  File "EmailHarvester.py", line 145, in process
    self.do_search()
  File "EmailHarvester.py", line 140, in do_search
    self.results = r.content.decode(r.encoding)
TypeError: decode() argument 1 must be str, not None

However when I run -e all -r dogpile everything is fine.

**Comment by maldevel** [comment]
fixed
